name: MarketSearch
main: au.com.addstar.marketsearch.MarketSearch
version: ${plugin.version}
api-version: ${spigot.api.version}
author: add5tar
softdepend: [Multiverse-Core, My_Worlds, QuickShop-Hikari, PlotMe, PlotSquared, Slimefun, Pandora, Monolith]
website:  ${project.url}
dev-url: ${project.url}
description: ${project.description}

commands:
  marketsearch:
    description: MarketSearch command 
    aliases: ms
    
permissions:
  marketsearch.find:
    description: Can search for items in the market (/ms find)
  marketsearch.stock:
    description: Can check own stock levels (/ms stock)
  marketsearch.stock.others:
    description: Can check other player's stock levels (/ms pstock)
    
