name: MarketSearch
main: au.com.addstar.marketsearch.MarketSearch
version: 1.2.0
author: add5tar
softdepend: [Essentials, Vault, Multiverse-Core, My Worlds, QuickShop, PlotMe]
website: http://dev.bukkit.org/server-mods/marketsearch/
dev-url: http://dev.bukkit.org/server-mods/marketsearch/
description: A set of helper commands to assist with QuickShop/PlotMe market worlds

commands:
  marketsearch:
    description: MarketSearch command 
    aliases: ms
    
permissions:
  marketsearch.find:
    description: Can search for items in the market (/ms find)
  marketsearch.stock:
    description: Can check own stock levels (/ms stock)
  marketsearch.stock.others:
    description: Can check other player's stock levels (/ms pstock)
    